# Parameters for Octomap (Octree map data structure).
#
# Paper link:
# http://www2.informatik.uni-freiburg.de/~stachnis/pdf/hornung13auro.pdf

# Fixed frame with which to express the map.
frame_id: world

# Leaf node voxel resolution (meters).
resolution: 0.5

sensor_model:
  min_range: 1.0
  max_range: 25.0

  # Sensor model's log-odds grid cell probability update for hits and misses
  # (from paper).
  miss: 0.4
  hit: 0.7

  # Occupancy clamping thresholds on the map (from paper).
  min: 0.12
  max: 0.97

# Calculation: size = resolution * 2^(max_depth), where size is the max size the
# octree can handle in any one dimension.
#
# From the paper, at a depth of 16 with resolution 1 cm, the octree can cover
# 655.36 meters in each direction. At a depth of 32 with resolution 1 cm, this
# increases to 42949672.96 meters in each direction.
max_depth: 16

# Remove noise in the map due to sensor noise.
filter_speckles: false

# Prune the tree upon laser scan insertions. This costs extra computation, but
# reduces memory usage.
compress_map: false
